### ISSUE TITLE
Question about Training Data Requirements

### ISSUE THREAD

**Issue by hmdolatabadi** [vincentfung13/MINE#2]
Hi,
Thanks for your interesting work.

I have a question regarding training data but I seem not to be able to find it in the paper.
Do you need ground truth depth maps during training or not?
Say I give you a purely image dataset like CIFAR-10, can you run your method on this data or it should contain "additional" information? If so, what is this "additional" information?

I know that during inference you only need the image, but I want to know what information is required during training.

Sincerely,
Hadi.

**Comment by vincentfung13** [comment]
Hi Hadi, 

Thank you for your interest in our work.

To train MINE, you will need a multi-view dataset, which means that for each scene, you will need to have a few images, along with their respective camera parameters (the focal length, principal point, rotation and translation, etc). You may use libraries like colmap to estimate these, but in that case, since the scale is ambiguous, you will also need a sparse set of 3D points for scale calibration (see Sec 3.3.1 of the paper).

You may check the example dataloader for more details: https://github.com/vincentfung13/MINE/blob/main/input_pipelines/llff/nerf_dataset.py

Hope this helps.

Zijian

**Comment by hmdolatabadi** [comment]
Dear Zijian,

Thanks for your prompt reply.
I have two follow-up questions:
1. By a few images for each scene, you mean how many? :D 
2. Reading through section 3.3.1, you say that I can use COLMAP to generate this set of 3D sparse points, right? Or for that I necessarily need videos of the scene?

I also have a suggestion: it would be lovely/much appreciated if you can provide a step-by-step guide in your repo readme on "how to train MINE for your own dataset".

Thanks again for your help.

Hadi.

**Comment by vincentfung13** [comment]
For question 1: 

In training, MINE requires only pairs of images of the same scene - one taken from the source camera (this is the input image to the network), the other as the target (this acts as the ground truth to supervise the training).

For question 2: 

The available datasets are sometimes available as stereo pairs (such as KITTI), in that case, the scale is fixed and the camera params are known, and you won't need to estimate the camera params or do the scale calibration mentioned in Sec 3.3.1 (thus no need for the point clouds as well). 

However, sometimes they are only available as monocular video sequences (such as RealEstate10K), in this case, the camera params are unknown, and you will need to run structure-from-motion (with COLMAP) to estimate them. This will introduce scale ambiguity, thus you will need the point clouds (obtained from SfM as well) and the scale calibration in training.

As for the step-by-step guide, again I suggest that you look at the dataloader: 

https://github.com/vincentfung13/MINE/blob/main/input_pipelines/llff/nerf_dataset.py

and try to run the code yourself (the instructions are already in the README file) for better understanding.

**Comment by hmdolatabadi** [comment]
Thanks for your thorough response.
