### ISSUE TITLE
KITTI traning code

### ISSUE THREAD

**Issue by zzyunzhi** [vincentfung13/MINE#6]
Hi, 
I was wondering if you plan to release KITTI training code at any time? 
Apart from this, are the released model checkpoints all pretrained on ImageNet? Thanks!

**Comment by vincentfung13** [comment]
Hi, 

- We do plan to release the training flows for the other datasets, but since we used some internal libraries from ByteDance, this will involve re-writing the dataloaders. Therefore, I don't have a precise estimation on when exactly we will be releasing them. But you are welcome to open an issue or drop us an email if you want to ask for any details or even request some code snippets. My apologies and thanks for your understanding.

- Yes, all the released models were trained with the encoder pretrained on ImageNet.

Hope this helps!

Zijian

**Comment by zzyunzhi** [comment]
Thank you for the reply! Closing the issue now.
